dist: bionic
language: node_js

node_js:
  - 14

cache: yarn

branches:
  only:
    - develop
addons:
  apt:
    update: true

install:
  - yarn install
  - cd support_scripts/grunt && npm install
  - cd ../..

script:
  - yarn coverage
